version: '2.1'
services:
  localstack:
    image: 'localstack/localstack:0.11.2'
    container_name: localstack
    ports:
      - '4566-4599:4566-4599'
      - 9000:9000
    environment:
      - HOSTNAME_EXTERNAL=localhost
      - HOSTNAME=localhost
      - HOST_TMP_FOLDER=/localstack
      - SERVICES=sqs,s3,sns
      - TEST_AWS_ACCOUNT_ID=foo
      - DEFAULT_REGION=ap-south-1
      - DATA_DIR=/tmp/localstack/data
      - PORT_WEB_UI=9000
      - LAMBDA_EXECUTOR=local
      - DOCKER_HOST=unix:///var/run/docker.sock
      - START_WEB=1
    volumes:
    - ./localstack:/tmp/localstack
    - ./docker.sock:/var/run/docker.sock
    - ./init-scripts:/docker-entrypoint-initaws.d
    tmpfs:
      - /localstack:exec,mode=600